export const cactus = [
  {
    part: "top",
    meshGroup: "A",
    name: "Flower Top",
    meshName: "AA00",
    flower: true,
  },
  {
    part: "top",
    meshGroup: "A",
    name: "Low Top",
    meshName: "AB00",
  },
  {
    part: "top",
    meshGroup: "A",
    name: "Medium Top",
    meshName: "AC00",
  },
  {
    part: "top",
    meshGroup: "A",
    name: "High Top",
    meshName: "AD00",
  },
  {
    part: "base",
    meshGroup: "B",
    name: "Pot",
    meshName: "BA00",
  },
  {
    part: "base",
    meshGroup: "B",
    name: "Cup",
    meshName: "BB00",
  },
  {
    part: "base",
    meshGroup: "B",
    name: "Vase",
    meshName: "BC00",
  },
  {
    part: "base",
    meshGroup: "B",
    name: "Geometry",
    meshName: "BD00",
  },
  {
    part: "leftArm",
    meshGroup: "C",
    name: "No Arm",
    meshName: "CA00",
  },
  {
    part: "leftArm",
    meshGroup: "C",
    name: "Short Arm",
    meshName: "CB00",
  },
  {
    part: "leftArm",
    meshGroup: "C",
    name: "Medium Arm",
    meshName: "CC00",
  },
  {
    part: "leftArm",
    meshGroup: "C",
    name: "Long Arm",
    meshName: "CD00",
  },
  {
    part: "rightArm",
    meshGroup: "D",
    name: "No Arm",
    meshName: "DA00",
  },
  {
    part: "rightArm",
    meshGroup: "D",
    name: "Short Arm",
    meshName: "DB00",
  },
  {
    part: "rightArm",
    meshGroup: "D",
    name: "Medium Arm",
    meshName: "DC00",
  },
  {
    part: "rightArm",
    meshGroup: "D",
    name: "Long Arm",
    meshName: "DD00",
  },
];
